# Generated by Django 4.2.5 on 2024-06-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="consultation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("online", "Online"),
                    ("offline", "Offline"),
                    ("both", "Both"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cardiologist", "Cardiologist"),
                    ("Dermatologist", "Dermatologist"),
                    ("Neurologist", "Neurologist"),
                    ("Orthopedic Surgeon", "Orthopedic Surgeon"),
                    ("Ophthalmologist", "Ophthalmologist"),
                    ("Gastroenterologist", "Gastroenterologist"),
                    ("Endocrinologist", "Endocrinologist"),
                    ("Pulmonologist", "Pulmonologist"),
                    ("Nephrologist", "Nephrologist"),
                    ("Pediatrician", "Pediatrician"),
                    ("Psychiatrist", "Psychiatrist"),
                    ("General", "General"),
                    ("Rheumatologist", "Rheumatologist"),
                    ("Hematologist", "Hematologist"),
                    ("Urologist", "Urologist"),
                    ("Otolaryngologist", "Otolaryngologist"),
                    ("Radiologist", "Radiologist"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="education",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="experience",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="medical_license",
            field=models.ImageField(
                blank=True, null=True, upload_to="medical_licenses/"
            ),
        ),
    ]
