# Generated by Django 4.2.5 on 2024-06-27 19:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "account",
            "0003_remove_user_consultation_type_remove_user_department_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "custom_id",
                    models.CharField(
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "specializations",
                    models.CharField(
                        choices=[
                            ("Cardiologist", "Cardiologist"),
                            ("Dermatologist", "Dermatologist"),
                            ("Neurologist", "Neurologist"),
                            ("Orthopedic Surgeon", "Orthopedic Surgeon"),
                            ("Ophthalmologist", "Ophthalmologist"),
                            ("Gastroenterologist", "Gastroenterologist"),
                            ("Endocrinologist", "Endocrinologist"),
                            ("Pulmonologist", "Pulmonologist"),
                            ("Nephrologist", "Nephrologist"),
                            ("Pediatrician", "Pediatrician"),
                            ("Psychiatrist", "Psychiatrist"),
                            ("General", "General"),
                            ("Rheumatologist", "Rheumatologist"),
                            ("Hematologist", "Hematologist"),
                            ("Urologist", "Urologist"),
                            ("Otolaryngologist", "Otolaryngologist"),
                            ("Radiologist", "Radiologist"),
                        ],
                        default="General",
                        max_length=30,
                    ),
                ),
                (
                    "consultaion_fees",
                    models.DecimalField(decimal_places=0, default=300, max_digits=10),
                ),
                (
                    "consultation_duration",
                    models.DurationField(default=datetime.timedelta(seconds=3600)),
                ),
                ("consultation_slots", models.IntegerField(default=5)),
                ("education", models.TextField(blank=True, max_length=50, null=True)),
                (
                    "college_name",
                    models.TextField(default="Not Available", max_length=50),
                ),
                ("years_of_experience", models.IntegerField(default=0)),
                ("about_me", models.CharField(blank=True, max_length=255, null=True)),
                ("Hospital", models.TextField(blank=True, max_length=50, null=True)),
                (
                    "consultation_time",
                    models.TextField(default="10AM to 5PM", max_length=50),
                ),
                ("rating", models.IntegerField(default=4)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
