# Generated by Django 4.2.5 on 2024-06-28 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="user",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
