# Generated by Django 4.2.5 on 2024-06-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_remove_patient_user_delete_doctor_delete_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                default="A+",
                max_length=5,
            ),
        ),
    ]
