# Generated by Django 4.2.5 on 2024-06-29 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_user_blood_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specializations",
                    models.CharField(
                        choices=[
                            ("Cardiologist", "Cardiologist"),
                            ("Dermatologist", "Dermatologist"),
                            ("Neurologist", "Neurologist"),
                            ("Orthopedic Surgeon", "Orthopedic Surgeon"),
                            ("Ophthalmologist", "Ophthalmologist"),
                            ("Gastroenterologist", "Gastroenterologist"),
                            ("Endocrinologist", "Endocrinologist"),
                            ("Pulmonologist", "Pulmonologist"),
                            ("Nephrologist", "Nephrologist"),
                            ("Pediatrician", "Pediatrician"),
                            ("Psychiatrist", "Psychiatrist"),
                            ("General", "General"),
                            ("Rheumatologist", "Rheumatologist"),
                            ("Hematologist", "Hematologist"),
                            ("Urologist", "Urologist"),
                            ("Otolaryngologist", "Otolaryngologist"),
                            ("Radiologist", "Radiologist"),
                        ],
                        default="General",
                        max_length=30,
                    ),
                ),
                ("education", models.TextField(blank=True, max_length=50, null=True)),
                ("years_of_experience", models.IntegerField(default=0)),
                ("about_me", models.CharField(blank=True, max_length=255, null=True)),
                ("Hospital", models.TextField(blank=True, max_length=50, null=True)),
                (
                    "consultaion_fees",
                    models.DecimalField(decimal_places=0, default=300, max_digits=10),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
