# Generated by Django 4.2.5 on 2024-06-29 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_doctor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="doc_verification",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aadhar_file",
                    models.FileField(
                        blank=True, null=True, upload_to="verification_documents/aadhar"
                    ),
                ),
                (
                    "degree_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="verification_documents/degree"
                    ),
                ),
                (
                    "experience_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="verification_documents/experience",
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
    ]
