# Generated by Django 5.0.6 on 2024-07-30 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0002_doctor_custom_id_user_custom_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receiver_type",
                    models.CharField(
                        choices=[("patient", "PATIENT"), ("doctor", "DOCTOR")],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("message", models.CharField(max_length=250, null=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("booked", "New Booked"),
                            ("pending", "New Pending"),
                            ("completed", "New Completed"),
                            ("cancelled", "New Cancelled"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_seen", models.BooleanField(default=False)),
                (
                    "Doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_from",
                        to="account.doctor",
                    ),
                ),
                (
                    "Patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
