# Generated by Django 5.0.6 on 2024-07-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="id",
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount",
            field=models.IntegerField(default=0, verbose_name="Amount"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="order_id",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Order ID"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_id",
            field=models.CharField(
                default="", max_length=200, verbose_name="Payment ID"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="signature",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Signature"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(
                default="",
                max_length=200,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Transaction ID",
            ),
            preserve_default=False,
        ),
    ]
