# Generated by Django 5.0.6 on 2024-08-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_transaction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_consultency_completed",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
