# Generated by Django 5.0.6 on 2024-08-09 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_transaction_is_consultency_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "doctor_commission_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.transaction",
                    ),
                ),
            ],
        ),
    ]
