# Generated by Django 5.0.6 on 2024-08-09 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_transactioncommission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactioncommission",
            name="transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commission",
                to="booking.transaction",
            ),
        ),
    ]
